/**
 * Category Aliases
 *
 * Maps alternative category names to canonical category IDs.
 * Extracted from knowledge.ts so runtime code (server.ts)
 * doesn't need to import the full knowledge base.
 */

export const categoryAliases: Record<string, string> = {
  'transactional email': 'email',
  'transactional-email': 'email',
  mail: 'email',
  smtp: 'email',
  payment: 'payments',
  'payment processing': 'payments',
  billing: 'payments',
  subscriptions: 'payments',
  authentication: 'auth',
  login: 'auth',
  'user management': 'auth',
  identity: 'auth',
  texting: 'sms',
  messaging: 'sms',
  'file storage': 'storage',
  uploads: 'storage',
  blobs: 'storage',
  s3: 'storage',
  postgres: 'database',
  mysql: 'database',
  db: 'database',
  sql: 'database',
  'error tracking': 'monitoring',
  observability: 'monitoring',
  logging: 'monitoring',
  apm: 'monitoring',
  'full-text search': 'search',
  'push notifications': 'push',
  notifications: 'push',
  llm: 'ai',
  'language model': 'ai',
  gpt: 'ai',
  claude: 'ai',
  'stock data': 'financial-data',
  'market data': 'financial-data',
  'stock api': 'financial-data',
  stocks: 'financial-data',
  'stock market': 'financial-data',
  'financial api': 'financial-data',
  finance: 'financial-data',
  'prediction market': 'prediction-markets',
  predictions: 'prediction-markets',
  forecasting: 'prediction-markets',
  polymarket: 'prediction-markets',
  kalshi: 'prediction-markets',
  'event contracts': 'prediction-markets',
  brokerage: 'trading',
  'stock trading': 'trading',
  'trade execution': 'trading',
  'order execution': 'trading',
  broker: 'trading',
  'buy stocks': 'trading',
  'sell stocks': 'trading',
  'crypto trading': 'trading',
  // New categories
  'env vars': 'secrets',
  'secret management': 'secrets',
  vault: 'secrets',
  'rate limit': 'rate-limiting',
  'rate limiter': 'rate-limiting',
  throttling: 'rate-limiting',
  geocoding: 'maps',
  mapping: 'maps',
  geolocation: 'maps',
  'video streaming': 'video',
  'video hosting': 'video',
  'live streaming': 'video',
  calendar: 'scheduling',
  booking: 'scheduling',
  appointments: 'scheduling',
  'background jobs': 'jobs',
  'job queue': 'jobs',
  'task queue': 'jobs',
  workers: 'jobs',
  cron: 'jobs',
};
