/**
 * Category Aliases
 *
 * Maps alternative category names to canonical category IDs.
 * Extracted from knowledge.ts so runtime code (server.ts)
 * doesn't need to import the full knowledge base.
 */

export const categoryAliases: Record<string, string> = {
  'transactional email': 'email',
  'transactional-email': 'email',
  mail: 'email',
  smtp: 'email',
  payment: 'payments',
  'payment processing': 'payments',
  billing: 'payments',
  subscriptions: 'payments',
  authentication: 'auth',
  login: 'auth',
  'user management': 'auth',
  identity: 'auth',
  texting: 'sms',
  messaging: 'sms',
  'file storage': 'storage',
  uploads: 'storage',
  blobs: 'storage',
  s3: 'storage',
  postgres: 'database',
  mysql: 'database',
  db: 'database',
  sql: 'database',
  'error tracking': 'monitoring',
  observability: 'monitoring',
  logging: 'monitoring',
  apm: 'monitoring',
  'full-text search': 'search',
  'push notifications': 'push',
  notifications: 'push',
  llm: 'ai',
  'language model': 'ai',
  gpt: 'ai',
  claude: 'ai',
  'stock data': 'financial-data',
  'market data': 'financial-data',
  'stock api': 'financial-data',
  stocks: 'financial-data',
  'stock market': 'financial-data',
  'financial api': 'financial-data',
  finance: 'financial-data',
  'prediction market': 'prediction-markets',
  predictions: 'prediction-markets',
  forecasting: 'prediction-markets',
  polymarket: 'prediction-markets',
  kalshi: 'prediction-markets',
  'event contracts': 'prediction-markets',
  brokerage: 'trading',
  'stock trading': 'trading',
  'trade execution': 'trading',
  'order execution': 'trading',
  broker: 'trading',
  'buy stocks': 'trading',
  'sell stocks': 'trading',
  'crypto trading': 'trading',
  // New categories
  'env vars': 'secrets',
  'secret management': 'secrets',
  vault: 'secrets',
  'rate limit': 'rate-limiting',
  'rate limiter': 'rate-limiting',
  throttling: 'rate-limiting',
  geocoding: 'maps',
  mapping: 'maps',
  geolocation: 'maps',
  'video streaming': 'video',
  'video hosting': 'video',
  'live streaming': 'video',
  calendar: 'scheduling',
  booking: 'scheduling',
  appointments: 'scheduling',
  'background jobs': 'jobs',
  'job queue': 'jobs',
  'task queue': 'jobs',
  workers: 'jobs',
  cron: 'jobs',
  // AI infrastructure
  'agent framework': 'ai-orchestration',
  'ai agents': 'ai-orchestration',
  langchain: 'ai-orchestration',
  'ai workflow': 'ai-orchestration',
  orchestration: 'ai-orchestration',
  'vector database': 'vector-db',
  'vector store': 'vector-db',
  embeddings: 'vector-db',
  pinecone: 'vector-db',
  rag: 'vector-db',
  'semantic search': 'vector-db',
  'document parsing': 'document-processing',
  'document extraction': 'document-processing',
  chunking: 'document-processing',
  ocr: 'document-processing',
  'pdf parsing': 'document-processing',
  'ai memory': 'ai-memory',
  'long-term memory': 'ai-memory',
  'context management': 'ai-memory',
  // Connectors & infrastructure
  'unified api': 'integrations',
  'api integration': 'integrations',
  crm: 'integrations',
  hris: 'integrations',
  'service connector': 'integrations',
  webhook: 'webhooks',
  'webhook delivery': 'webhooks',
  'event delivery': 'webhooks',
  'api gateway': 'api-gateway',
  'api management': 'api-gateway',
  'api proxy': 'api-gateway',
  'audit log': 'audit-logging',
  'audit trail': 'audit-logging',
  compliance: 'audit-logging',
  governance: 'audit-logging',
  // AI generation
  'text to speech': 'ai-audio',
  tts: 'ai-audio',
  'speech to text': 'ai-audio',
  stt: 'ai-audio',
  'audio generation': 'ai-audio',
  'voice ai': 'ai-audio',
  'voice synthesis': 'ai-audio',
  transcription: 'ai-audio',
  'music generation': 'ai-audio',
  'video generation': 'ai-video',
  'text to video': 'ai-video',
  'ai video': 'ai-video',
  'video ai': 'ai-video',
  'image generation': 'ai-image',
  'text to image': 'ai-image',
  'ai image': 'ai-image',
  'image ai': 'ai-image',
  diffusion: 'ai-image',
  'stable diffusion': 'ai-image',
  dall_e: 'ai-image',
  midjourney: 'ai-image',
  // Infrastructure additions
  'feature flag': 'feature-flags',
  'feature flags': 'feature-flags',
  'feature toggle': 'feature-flags',
  'a/b testing': 'feature-flags',
  'message queue': 'message-queue',
  'message broker': 'message-queue',
  kafka: 'message-queue',
  rabbitmq: 'message-queue',
  pubsub: 'message-queue',
  'event streaming': 'message-queue',
  cache: 'cache-kv',
  redis: 'cache-kv',
  memcached: 'cache-kv',
  'key value': 'cache-kv',
  kv: 'cache-kv',
  'in memory': 'cache-kv',
  realtime: 'realtime',
  websocket: 'realtime',
  websockets: 'realtime',
  'server sent events': 'realtime',
  sse: 'realtime',
  'live updates': 'realtime',
  presence: 'realtime',
};
