import type { KnownProvider } from './types.js';

// Curated knowledge of API providers per category
// This enables instant recommendations without web search
//
// DATA PHILOSOPHY:
// - Store the RICHEST data available (exact prices, benchmark scores, dates)
// - LLM derives tiers/simplifications at match time
// - All metrics include measurement date for freshness tracking
// - Pricing includes source URLs for verification

export const knowledgeBase: Record<string, KnownProvider[]> = {
  email: [
    {
      name: 'Resend',
      package: 'resend',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Postmark',
      package: 'postmark',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: false,
      hasSdk: true,
    },
    {
      name: 'SendGrid',
      package: '@sendgrid/mail',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Amazon SES',
      package: '@aws-sdk/client-ses',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['growth', 'enterprise'],
      strengths: ['cost', 'performance'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'aws',
    },
    {
      name: 'Mailgun',
      package: 'mailgun.js',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['dx', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  payments: [
    {
      name: 'Stripe',
      package: 'stripe',
      compliance: ['SOC2', 'PCI-DSS', 'GDPR'],
      scale: ['hobby', 'startup', 'growth', 'enterprise'],
      strengths: ['dx', 'reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Paddle',
      package: '@paddle/paddle-node-sdk',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth'],
      strengths: ['dx', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'LemonSqueezy',
      package: '@lemonsqueezy/lemonsqueezy.js',
      compliance: ['GDPR'],
      scale: ['hobby', 'startup'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  auth: [
    {
      name: 'Clerk',
      package: '@clerk/nextjs',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Auth0',
      package: '@auth0/nextjs-auth0',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Supabase Auth',
      package: '@supabase/supabase-js',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'supabase',
    },
    {
      name: 'NextAuth.js',
      package: 'next-auth',
      compliance: [],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  sms: [
    {
      name: 'Twilio',
      package: 'twilio',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'MessageBird',
      package: 'messagebird',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  storage: [
    {
      name: 'Cloudflare R2',
      package: '@aws-sdk/client-s3',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth', 'enterprise'],
      strengths: ['cost', 'performance'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'cloudflare',
    },
    {
      name: 'AWS S3',
      package: '@aws-sdk/client-s3',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'performance'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'aws',
    },
    {
      name: 'Uploadthing',
      package: 'uploadthing',
      compliance: ['GDPR'],
      scale: ['hobby', 'startup'],
      strengths: ['dx'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  database: [
    {
      name: 'Supabase',
      package: '@supabase/supabase-js',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'supabase',
    },
    {
      name: 'PlanetScale',
      package: '@planetscale/database',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['performance', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Neon',
      package: '@neondatabase/serverless',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  analytics: [
    {
      name: 'PostHog',
      package: 'posthog-js',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth', 'enterprise'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Mixpanel',
      package: 'mixpanel',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Amplitude',
      package: '@amplitude/analytics-node',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  search: [
    {
      name: 'Algolia',
      package: 'algoliasearch',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['dx', 'performance'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Typesense',
      package: 'typesense',
      compliance: ['GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Meilisearch',
      package: 'meilisearch',
      compliance: ['GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
  ],

  monitoring: [
    {
      name: 'Sentry',
      package: '@sentry/nextjs',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth', 'enterprise'],
      strengths: ['dx', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Datadog',
      package: 'dd-trace',
      compliance: ['SOC2', 'HIPAA', 'GDPR'],
      scale: ['growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      hasFreeTier: false,
      hasSdk: true,
    },
  ],

  ai: [
    {
      id: 'openai-gpt4o',
      name: 'OpenAI GPT-4o',
      description: 'Multimodal flagship model with vision, audio, and tool calling',
      website: 'https://openai.com',
      docsUrl: 'https://platform.openai.com/docs',
      category: 'ai',
      subcategories: ['llm', 'multimodal', 'chat'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'openai',
      packageAltNames: {
        python: 'openai',
        go: 'github.com/openai/openai-go',
        dotnet: 'Azure.AI.OpenAI',
      },
      platforms: [
        { platform: 'server', sdkPackage: 'openai', maturity: 'mature' },
        { platform: 'web', sdkPackage: 'openai', maturity: 'stable', notes: 'Use edge runtime or proxy' },
        { platform: 'react-native', maturity: 'stable', notes: 'Via REST or expo config' },
      ],
      compliance: ['SOC2', 'GDPR', 'CCPA'],
      dataResidency: ['US', 'EU'],
      pricing: {
        type: 'usage',
        currency: 'USD',
        unitPricing: {
          unit: '1M tokens',
          price: 2.50,  // input tokens
          volumeDiscounts: [
            { threshold: 100000000, pricePerUnit: 1.25 },  // batch API
          ],
        },
        lastVerified: '2025-01-29',
        source: 'https://openai.com/api/pricing/',
      },
      latency: {
        p50Ms: 800,
        p95Ms: 2500,
        measuredAt: '2025-01-15',
        source: 'Artificial Analysis',
        region: 'US',
      },
      reliability: {
        uptimeSla: 99.9,
        statusPageUrl: 'https://status.openai.com',
        measuredAt: '2025-01-29',
      },
      aiBenchmarks: {
        lmArena: {
          elo: 1285,
          rank: 3,
          category: 'overall',
          measuredAt: '2025-01-20',
        },
        artificialAnalysis: {
          qualityIndex: 78,
          speedIndex: 65,
          pricePerMToken: 2.50,
          tokensPerSecond: 109,
          ttft: 320,
          measuredAt: '2025-01-15',
        },
        benchmarks: [
          { name: 'MMLU', score: 88.7, maxScore: 100, measuredAt: '2024-12-01' },
          { name: 'HumanEval', score: 90.2, maxScore: 100, measuredAt: '2024-12-01' },
          { name: 'GPQA', score: 53.6, maxScore: 100, measuredAt: '2024-12-01' },
        ],
        contextWindow: {
          maxTokens: 128000,
          effectiveTokens: 64000,
        },
        capabilities: {
          toolCalling: true,
          vision: true,
          audio: true,
          streaming: true,
          jsonMode: true,
          functionCalling: true,
        },
      },
      bestFor: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'performance', 'dx'],
      weaknesses: ['cost at scale', 'privacy concerns for sensitive data'],
      avoidIf: ['strict on-prem requirement', 'need EU-only data residency'],
      requires: ['internet', 'api_key'],
      bestWhen: ['need multimodal', 'tool calling heavy', 'production reliability'],
      alternatives: ['anthropic-claude-sonnet', 'google-gemini-pro'],
    },
    {
      id: 'anthropic-claude-sonnet',
      name: 'Anthropic Claude 3.5 Sonnet',
      description: 'Best coding model, strong reasoning, 200K context',
      website: 'https://anthropic.com',
      docsUrl: 'https://docs.anthropic.com',
      category: 'ai',
      subcategories: ['llm', 'coding', 'chat'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@anthropic-ai/sdk',
      packageAltNames: {
        python: 'anthropic',
        go: 'github.com/anthropics/anthropic-sdk-go',
      },
      platforms: [
        { platform: 'server', sdkPackage: '@anthropic-ai/sdk', maturity: 'mature' },
        { platform: 'web', maturity: 'stable', notes: 'Via proxy or edge' },
      ],
      compliance: ['SOC2', 'GDPR', 'HIPAA'],
      pricing: {
        type: 'usage',
        currency: 'USD',
        unitPricing: {
          unit: '1M tokens',
          price: 3.00,  // input
        },
        lastVerified: '2025-01-29',
        source: 'https://anthropic.com/pricing',
      },
      latency: {
        p50Ms: 600,
        p95Ms: 1800,
        measuredAt: '2025-01-15',
        source: 'Artificial Analysis',
      },
      aiBenchmarks: {
        lmArena: {
          elo: 1271,
          rank: 6,
          category: 'overall',
          measuredAt: '2025-01-20',
        },
        artificialAnalysis: {
          qualityIndex: 75,
          speedIndex: 72,
          pricePerMToken: 3.00,
          tokensPerSecond: 87,
          ttft: 480,
          measuredAt: '2025-01-15',
        },
        benchmarks: [
          { name: 'HumanEval', score: 92.0, maxScore: 100, measuredAt: '2024-10-01' },
          { name: 'GPQA', score: 65.0, maxScore: 100, measuredAt: '2024-10-01' },
        ],
        contextWindow: {
          maxTokens: 200000,
          effectiveTokens: 100000,
        },
        capabilities: {
          toolCalling: true,
          vision: true,
          streaming: true,
          jsonMode: true,
        },
      },
      bestFor: ['startup', 'growth', 'enterprise'],
      strengths: ['dx', 'performance', 'reliability'],
      weaknesses: ['no audio input', 'slightly higher cost'],
      avoidIf: ['need audio/speech', 'budget constrained'],
      requires: ['internet', 'api_key'],
      bestWhen: ['coding tasks', 'long context', 'complex reasoning'],
      alternatives: ['openai-gpt4o', 'google-gemini-pro'],
    },
    {
      id: 'google-gemini-flash',
      name: 'Google Gemini 2.0 Flash',
      description: 'Fast, cheap multimodal with strong performance',
      website: 'https://ai.google.dev',
      docsUrl: 'https://ai.google.dev/docs',
      category: 'ai',
      subcategories: ['llm', 'multimodal', 'chat'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@google/generative-ai',
      platforms: [
        { platform: 'server', sdkPackage: '@google/generative-ai', maturity: 'stable' },
        { platform: 'web', maturity: 'stable' },
      ],
      compliance: ['SOC2', 'GDPR'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '15 RPM, 1M tokens/day',
          limitations: ['rate limited', 'no SLA'],
        },
        unitPricing: {
          unit: '1M tokens',
          price: 0.075,
        },
        lastVerified: '2025-01-29',
        source: 'https://ai.google.dev/pricing',
      },
      aiBenchmarks: {
        lmArena: {
          elo: 1354,
          rank: 2,
          category: 'overall',
          measuredAt: '2025-01-20',
        },
        artificialAnalysis: {
          qualityIndex: 71,
          speedIndex: 92,
          pricePerMToken: 0.075,
          tokensPerSecond: 450,
          ttft: 150,
          measuredAt: '2025-01-15',
        },
        contextWindow: {
          maxTokens: 1000000,
          effectiveTokens: 200000,
        },
        capabilities: {
          toolCalling: true,
          vision: true,
          audio: true,
          streaming: true,
          jsonMode: true,
        },
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['cost', 'performance', 'dx'],
      weaknesses: ['newer SDK', 'less enterprise adoption'],
      avoidIf: ['need HIPAA'],
      requires: ['internet', 'api_key'],
      bestWhen: ['cost sensitive', 'high volume', 'need speed'],
      alternatives: ['openai-gpt4o-mini', 'anthropic-claude-haiku'],
    },
    {
      id: 'vercel-ai-sdk',
      name: 'Vercel AI SDK',
      description: 'Universal SDK for multiple AI providers with streaming UI helpers',
      website: 'https://sdk.vercel.ai',
      docsUrl: 'https://sdk.vercel.ai/docs',
      category: 'ai',
      subcategories: ['sdk', 'streaming', 'ui'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'ai',
      platforms: [
        { platform: 'server', sdkPackage: 'ai', maturity: 'mature' },
        { platform: 'web', sdkPackage: '@ai-sdk/react', maturity: 'mature' },
        { platform: 'edge', sdkPackage: 'ai', maturity: 'mature' },
      ],
      compliance: [],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Unlimited (SDK only)',
          limitations: ['Provider costs still apply'],
        },
        lastVerified: '2025-01-29',
        source: 'https://sdk.vercel.ai',
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'reliability'],
      weaknesses: ['not a model itself', 'vercel ecosystem coupling'],
      avoidIf: ['need raw API access', 'not using React/Next.js'],
      requires: ['separate AI provider API key'],
      bestWhen: ['building chat UI', 'need streaming', 'using Next.js'],
      alternatives: ['langchain', 'llamaindex'],
      ecosystem: 'vercel',
    },
  ],

  push: [
    {
      name: 'OneSignal',
      package: '@onesignal/node-onesignal',
      compliance: ['SOC2', 'GDPR'],
      scale: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'cost'],
      hasFreeTier: true,
      hasSdk: true,
    },
    {
      name: 'Firebase Cloud Messaging',
      package: 'firebase-admin',
      compliance: ['SOC2', 'GDPR'],
      scale: ['hobby', 'startup', 'growth'],
      strengths: ['cost', 'reliability'],
      hasFreeTier: true,
      hasSdk: true,
      ecosystem: 'firebase',
    },
  ],

  'financial-data': [
    {
      id: 'finnhub',
      name: 'Finnhub',
      description: 'Real-time stock, forex, crypto data with news and sentiment',
      website: 'https://finnhub.io',
      docsUrl: 'https://finnhub.io/docs/api',
      category: 'financial-data',
      subcategories: ['stocks', 'forex', 'crypto', 'news', 'fundamentals'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'finnhub',
      platforms: [
        { platform: 'server', sdkPackage: 'finnhub', maturity: 'stable' },
        { platform: 'web', maturity: 'stable', notes: 'Via proxy recommended' },
      ],
      compliance: ['GDPR'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '60 API calls/minute',
          limitations: ['US stocks only', 'no premium data'],
        },
        plans: [
          { name: 'Free', priceMonthly: 0, includes: '60 calls/min, basic data' },
          { name: 'Starter', priceMonthly: 49, includes: '300 calls/min, more markets' },
          { name: 'Professional', priceMonthly: 149, includes: 'Full access' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://finnhub.io/pricing',
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost', 'reliability'],
      weaknesses: ['rate limits on free tier', 'no real-time for free'],
      avoidIf: ['need tick-level data', 'need extensive historical'],
      requires: ['api_key'],
      bestWhen: ['need news + sentiment', 'building dashboards', 'mixed data needs'],
      alternatives: ['alpha-vantage', 'polygon'],
    },
    {
      id: 'alpha-vantage',
      name: 'Alpha Vantage',
      description: 'Historical stock data, technical indicators, forex, crypto',
      website: 'https://www.alphavantage.co',
      docsUrl: 'https://www.alphavantage.co/documentation/',
      category: 'financial-data',
      subcategories: ['stocks', 'forex', 'crypto', 'technical-analysis'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'alphavantage',
      platforms: [
        { platform: 'server', sdkPackage: 'alphavantage', maturity: 'stable' },
      ],
      compliance: ['GDPR'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '25 API calls/day',
          limitations: ['very limited requests', 'delayed data'],
        },
        plans: [
          { name: 'Free', priceMonthly: 0, includes: '25 calls/day' },
          { name: 'Premium', priceMonthly: 49.99, includes: '75 calls/min' },
          { name: 'Premium+', priceMonthly: 99.99, includes: '150 calls/min' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://www.alphavantage.co/premium/',
      },
      bestFor: ['hobby', 'startup'],
      strengths: ['cost', 'dx'],
      weaknesses: ['harsh rate limits', 'slow for production'],
      avoidIf: ['need real-time', 'high volume'],
      requires: ['api_key'],
      bestWhen: ['backtesting', 'technical analysis', 'learning'],
      alternatives: ['finnhub', 'eodhd'],
    },
    {
      id: 'polygon',
      name: 'Polygon.io',
      description: 'Real-time and historical market data with WebSocket streaming',
      website: 'https://polygon.io',
      docsUrl: 'https://polygon.io/docs',
      category: 'financial-data',
      subcategories: ['stocks', 'options', 'forex', 'crypto', 'real-time'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@polygon.io/client-js',
      platforms: [
        { platform: 'server', sdkPackage: '@polygon.io/client-js', maturity: 'mature' },
        { platform: 'web', maturity: 'stable' },
      ],
      compliance: ['SOC2', 'GDPR'],
      pricing: {
        type: 'tiered',
        currency: 'USD',
        freeTier: {
          included: '5 API calls/minute',
          limitations: ['very limited', 'delayed data'],
        },
        plans: [
          { name: 'Basic', priceMonthly: 29, includes: 'Unlimited delayed' },
          { name: 'Starter', priceMonthly: 79, includes: 'Real-time stocks' },
          { name: 'Developer', priceMonthly: 199, includes: 'All real-time' },
          { name: 'Advanced', priceMonthly: 399, includes: 'Full historical' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://polygon.io/pricing',
      },
      bestFor: ['startup', 'growth', 'enterprise'],
      strengths: ['performance', 'reliability', 'dx'],
      weaknesses: ['expensive', 'overkill for simple needs'],
      avoidIf: ['budget constrained', 'only need basic data'],
      requires: ['api_key'],
      bestWhen: ['real-time trading apps', 'need WebSocket', 'production systems'],
      alternatives: ['finnhub', 'alpaca'],
    },
    {
      id: 'fmp',
      name: 'Financial Modeling Prep',
      description: 'Financial statements, company fundamentals, SEC filings',
      website: 'https://site.financialmodelingprep.com',
      docsUrl: 'https://site.financialmodelingprep.com/developer/docs',
      category: 'financial-data',
      subcategories: ['fundamentals', 'sec-filings', 'financials', 'valuation'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'financialmodelingprep',
      platforms: [
        { platform: 'server', maturity: 'stable' },
      ],
      compliance: ['GDPR'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '250 API calls/day',
          limitations: ['limited endpoints'],
        },
        plans: [
          { name: 'Basic', priceMonthly: 29, includes: 'Full access' },
          { name: 'Professional', priceMonthly: 99, includes: 'Priority support' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://site.financialmodelingprep.com/developer/docs/pricing',
      },
      bestFor: ['startup', 'growth'],
      strengths: ['dx', 'cost'],
      weaknesses: ['no real-time prices', 'fundamentals focused'],
      avoidIf: ['need real-time prices', 'need technical data'],
      requires: ['api_key'],
      bestWhen: ['fundamental analysis', 'valuation models', 'financial statements'],
      alternatives: ['finnhub', 'eodhd'],
    },
    {
      id: 'alpaca',
      name: 'Alpaca Markets',
      description: 'Commission-free trading API with free market data',
      website: 'https://alpaca.markets',
      docsUrl: 'https://docs.alpaca.markets',
      category: 'financial-data',
      subcategories: ['stocks', 'trading', 'real-time', 'paper-trading'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@alpacahq/alpaca-trade-api',
      platforms: [
        { platform: 'server', sdkPackage: '@alpacahq/alpaca-trade-api', maturity: 'mature' },
      ],
      compliance: ['SOC2', 'FINRA', 'SEC'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Unlimited (IEX data)',
          limitations: ['IEX-only quotes', 'US stocks only'],
        },
        plans: [
          { name: 'Algo Trader Plus', priceMonthly: 99, includes: 'Full SIP data' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://alpaca.markets/pricing',
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['cost', 'dx', 'reliability'],
      weaknesses: ['US-only', 'limited to stocks'],
      avoidIf: ['need international markets', 'need forex/crypto'],
      requires: ['api_key', 'account'],
      bestWhen: ['building trading bots', 'paper trading', 'US stocks focus'],
      alternatives: ['polygon', 'tradier'],
      ecosystem: 'alpaca',
    },
  ],

  trading: [
    {
      id: 'alpaca-trading',
      name: 'Alpaca',
      description: 'Commission-free stock and crypto trading API with paper trading',
      website: 'https://alpaca.markets',
      docsUrl: 'https://docs.alpaca.markets',
      category: 'trading',
      subcategories: ['stocks', 'crypto', 'paper-trading', 'fractional-shares'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@alpacahq/alpaca-trade-api',
      platforms: [
        { platform: 'server', sdkPackage: '@alpacahq/alpaca-trade-api', maturity: 'mature' },
      ],
      compliance: ['SOC2', 'FINRA', 'SEC'],
      dataResidency: ['US'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Commission-free trading',
          limitations: ['US stocks only', 'no options'],
        },
        lastVerified: '2025-01-29',
        source: 'https://alpaca.markets/pricing',
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['cost', 'dx', 'reliability'],
      weaknesses: ['US-only', 'no options', 'limited asset classes'],
      avoidIf: ['need international', 'need options trading'],
      requires: ['api_key', 'brokerage_account'],
      bestWhen: ['algorithmic trading', 'building trading apps', 'paper trading'],
      alternatives: ['tradier', 'interactive-brokers'],
      ecosystem: 'alpaca',
    },
    {
      id: 'tradier',
      name: 'Tradier',
      description: 'Brokerage API for stocks and options with OAuth integration',
      website: 'https://tradier.com',
      docsUrl: 'https://documentation.tradier.com',
      category: 'trading',
      subcategories: ['stocks', 'options', 'etfs'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'tradier',
      platforms: [
        { platform: 'server', maturity: 'stable' },
      ],
      compliance: ['FINRA', 'SEC', 'SIPC'],
      dataResidency: ['US'],
      pricing: {
        type: 'tiered',
        currency: 'USD',
        plans: [
          { name: 'Individual', priceMonthly: 0, includes: '$0 equity trades, $0.35/option' },
          { name: 'Developer', priceMonthly: 10, includes: 'Sandbox access' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://tradier.com/pricing',
      },
      bestFor: ['startup', 'growth'],
      strengths: ['dx', 'cost', 'reliability'],
      weaknesses: ['US-only', 'smaller ecosystem'],
      avoidIf: ['need international markets', 'need crypto'],
      requires: ['api_key', 'brokerage_account'],
      bestWhen: ['options trading apps', 'need OAuth flow', 'white-label brokerage'],
      alternatives: ['alpaca', 'interactive-brokers'],
    },
    {
      id: 'interactive-brokers',
      name: 'Interactive Brokers',
      description: 'Professional-grade multi-asset trading across global markets',
      website: 'https://www.interactivebrokers.com',
      docsUrl: 'https://www.interactivebrokers.com/en/trading/ib-api.php',
      category: 'trading',
      subcategories: ['stocks', 'options', 'futures', 'forex', 'bonds', 'global'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'ib-insync',
      packageAltNames: {
        python: 'ib-insync',
        java: 'TWS API',
      },
      platforms: [
        { platform: 'server', maturity: 'mature', notes: 'TWS or IB Gateway required' },
      ],
      compliance: ['SOC2', 'FINRA', 'SEC', 'FCA', 'MiFID'],
      dataResidency: ['US', 'EU', 'APAC'],
      pricing: {
        type: 'tiered',
        currency: 'USD',
        plans: [
          { name: 'IBKR Lite', priceMonthly: 0, includes: 'Commission-free US stocks' },
          { name: 'IBKR Pro', priceMonthly: 0, includes: 'Tiered pricing, global access' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://www.interactivebrokers.com/en/pricing/commissions-home.php',
      },
      bestFor: ['growth', 'enterprise'],
      strengths: ['reliability', 'performance'],
      weaknesses: ['complex API', 'steep learning curve', 'requires TWS/Gateway'],
      avoidIf: ['simple use case', 'need quick integration', 'hobby project'],
      requires: ['api_key', 'brokerage_account', 'tws_or_gateway'],
      bestWhen: ['professional trading', 'global markets', 'multi-asset strategies'],
      alternatives: ['alpaca', 'tradier'],
    },
    {
      id: 'schwab',
      name: 'Charles Schwab',
      description: 'Major brokerage API (formerly TD Ameritrade) with OAuth',
      website: 'https://www.schwab.com',
      docsUrl: 'https://developer.schwab.com',
      category: 'trading',
      subcategories: ['stocks', 'options', 'etfs', 'mutual-funds'],
      status: 'active',
      lastVerified: '2025-01-29',
      platforms: [
        { platform: 'server', maturity: 'stable' },
      ],
      compliance: ['FINRA', 'SEC', 'SIPC'],
      dataResidency: ['US'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '$0 online stock/ETF trades',
          limitations: ['$0.65/option contract'],
        },
        lastVerified: '2025-01-29',
        source: 'https://www.schwab.com/pricing',
      },
      bestFor: ['growth', 'enterprise'],
      strengths: ['reliability', 'support'],
      weaknesses: ['API approval process', 'less dev-friendly'],
      avoidIf: ['need quick integration', 'startup'],
      requires: ['api_key', 'brokerage_account', 'api_approval'],
      bestWhen: ['established fintech', 'high net worth clients', 'full-service brokerage'],
      alternatives: ['tradier', 'alpaca'],
    },
    {
      id: 'coinbase-exchange',
      name: 'Coinbase Advanced Trade',
      description: 'Crypto trading API with spot and derivatives',
      website: 'https://www.coinbase.com',
      docsUrl: 'https://docs.cloud.coinbase.com/advanced-trade-api',
      category: 'trading',
      subcategories: ['crypto', 'spot', 'derivatives'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'coinbase-advanced-py',
      packageAltNames: {
        python: 'coinbase-advanced-py',
      },
      platforms: [
        { platform: 'server', maturity: 'mature' },
        { platform: 'web', maturity: 'stable', notes: 'Via proxy' },
      ],
      compliance: ['SOC2', 'FinCEN', 'NYDFS'],
      dataResidency: ['US'],
      pricing: {
        type: 'tiered',
        currency: 'USD',
        plans: [
          { name: 'Standard', priceMonthly: 0, includes: '0.6% maker / 1.2% taker' },
          { name: 'Advanced', priceMonthly: 0, includes: 'Volume-based discounts' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://help.coinbase.com/en/advanced-trade/trading-and-funding/advanced-trade-fees',
      },
      bestFor: ['startup', 'growth', 'enterprise'],
      strengths: ['reliability', 'dx', 'security'],
      weaknesses: ['crypto-only', 'US restrictions on some products'],
      avoidIf: ['need stocks', 'outside US'],
      requires: ['api_key', 'coinbase_account'],
      bestWhen: ['crypto trading apps', 'need US compliance', 'institutional crypto'],
      alternatives: ['binance', 'kraken'],
    },
  ],

  'prediction-markets': [
    {
      id: 'kalshi',
      name: 'Kalshi',
      description: 'CFTC-regulated prediction market with REST, WebSocket, and FIX APIs',
      website: 'https://kalshi.com',
      docsUrl: 'https://trading-api.readme.io/reference',
      category: 'prediction-markets',
      subcategories: ['politics', 'economics', 'weather', 'entertainment'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: 'kalshi-python',
      packageAltNames: {
        python: 'kalshi-python',
      },
      platforms: [
        { platform: 'server', maturity: 'stable' },
      ],
      compliance: ['CFTC'],
      dataResidency: ['US'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Full API access',
          limitations: ['trading fees apply'],
        },
        lastVerified: '2025-01-29',
        source: 'https://kalshi.com/fees',
      },
      bestFor: ['startup', 'growth'],
      strengths: ['reliability', 'dx'],
      weaknesses: ['US-only', '30-min token expiry'],
      avoidIf: ['non-US users', 'need crypto settlement'],
      requires: ['api_key', 'account', 'US residency'],
      bestWhen: ['regulated markets needed', 'building fintech', 'fiat integration'],
      alternatives: ['polymarket', 'metaculus'],
    },
    {
      id: 'polymarket',
      name: 'Polymarket',
      description: 'Crypto-based prediction market with REST and WebSocket APIs',
      website: 'https://polymarket.com',
      docsUrl: 'https://docs.polymarket.com',
      category: 'prediction-markets',
      subcategories: ['politics', 'crypto', 'sports', 'entertainment'],
      status: 'active',
      lastVerified: '2025-01-29',
      package: '@polymarket/clob-client',
      platforms: [
        { platform: 'server', sdkPackage: '@polymarket/clob-client', maturity: 'stable' },
        { platform: 'web', maturity: 'stable', notes: 'Web3 wallet required' },
      ],
      compliance: [],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: '1000 calls/hour (non-trading)',
          limitations: ['rate limited'],
        },
        plans: [
          { name: 'Premium', priceMonthly: 99, includes: 'WebSocket + full historical' },
        ],
        lastVerified: '2025-01-29',
        source: 'https://docs.polymarket.com',
      },
      bestFor: ['hobby', 'startup', 'growth'],
      strengths: ['dx', 'cost'],
      weaknesses: ['crypto-only', 'regulatory uncertainty', 'US restrictions'],
      avoidIf: ['need fiat settlement', 'regulatory concerns', 'US users'],
      requires: ['api_key', 'crypto_wallet'],
      bestWhen: ['crypto native', 'need more markets', 'permissionless access'],
      alternatives: ['kalshi', 'manifold'],
    },
    {
      id: 'metaculus',
      name: 'Metaculus',
      description: 'Community forecasting platform with prediction aggregation',
      website: 'https://www.metaculus.com',
      docsUrl: 'https://www.metaculus.com/api/',
      category: 'prediction-markets',
      subcategories: ['forecasting', 'science', 'technology', 'geopolitics'],
      status: 'active',
      lastVerified: '2025-01-29',
      platforms: [
        { platform: 'server', maturity: 'stable' },
      ],
      compliance: ['GDPR'],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Full read access',
          limitations: ['rate limited'],
        },
        lastVerified: '2025-01-29',
        source: 'https://www.metaculus.com/api/',
      },
      bestFor: ['hobby', 'startup'],
      strengths: ['cost', 'dx'],
      weaknesses: ['no trading', 'forecasts only'],
      avoidIf: ['need tradeable contracts', 'need real-time'],
      requires: ['api_key'],
      bestWhen: ['research', 'worldview analysis', 'long-term forecasts'],
      alternatives: ['kalshi', 'polymarket'],
    },
    {
      id: 'manifold',
      name: 'Manifold Markets',
      description: 'Play-money prediction market with open API',
      website: 'https://manifold.markets',
      docsUrl: 'https://docs.manifold.markets/api',
      category: 'prediction-markets',
      subcategories: ['politics', 'technology', 'sports', 'custom'],
      status: 'active',
      lastVerified: '2025-01-29',
      platforms: [
        { platform: 'server', maturity: 'stable' },
        { platform: 'web', maturity: 'stable' },
      ],
      compliance: [],
      pricing: {
        type: 'freemium',
        currency: 'USD',
        freeTier: {
          included: 'Unlimited',
          limitations: ['play money only'],
        },
        lastVerified: '2025-01-29',
        source: 'https://manifold.markets',
      },
      bestFor: ['hobby', 'startup'],
      strengths: ['cost', 'dx'],
      weaknesses: ['play money', 'less liquidity'],
      avoidIf: ['need real trading', 'need deep liquidity'],
      requires: [],
      bestWhen: ['prototyping', 'testing', 'custom markets'],
      alternatives: ['polymarket', 'metaculus'],
    },
  ],
};

// Category aliases for flexible matching
export const categoryAliases: Record<string, string> = {
  'transactional email': 'email',
  'transactional-email': 'email',
  mail: 'email',
  smtp: 'email',
  payment: 'payments',
  'payment processing': 'payments',
  billing: 'payments',
  subscriptions: 'payments',
  authentication: 'auth',
  login: 'auth',
  'user management': 'auth',
  identity: 'auth',
  texting: 'sms',
  messaging: 'sms',
  'file storage': 'storage',
  uploads: 'storage',
  blobs: 'storage',
  s3: 'storage',
  postgres: 'database',
  mysql: 'database',
  db: 'database',
  sql: 'database',
  'error tracking': 'monitoring',
  observability: 'monitoring',
  logging: 'monitoring',
  apm: 'monitoring',
  'full-text search': 'search',
  'push notifications': 'push',
  notifications: 'push',
  llm: 'ai',
  'language model': 'ai',
  gpt: 'ai',
  claude: 'ai',
  // Financial data aliases
  'stock data': 'financial-data',
  'market data': 'financial-data',
  'stock api': 'financial-data',
  stocks: 'financial-data',
  'stock market': 'financial-data',
  'financial api': 'financial-data',
  finance: 'financial-data',
  // Prediction markets aliases
  'prediction market': 'prediction-markets',
  'predictions': 'prediction-markets',
  forecasting: 'prediction-markets',
  polymarket: 'prediction-markets',
  kalshi: 'prediction-markets',
  'event contracts': 'prediction-markets',
  // Trading aliases
  brokerage: 'trading',
  'stock trading': 'trading',
  'trade execution': 'trading',
  'order execution': 'trading',
  broker: 'trading',
  'buy stocks': 'trading',
  'sell stocks': 'trading',
  'crypto trading': 'trading',
};
